#!/usr/bin/env ruby

file = ARGV.shift
if file.nil? 
  puts "Usage: ruby runner.rb sequence.fasta"
  exit -1
end

puts "Moving file in place..."
system("mv --update #{file} input.fasta")
puts "Creating SVG file \"test.svg\" from sequence..."
system("rasem test.rasem")
puts "Converting SVG file to PNG file \"#{file}.png\"..."
system("convert -density 700 test.svg #{file}.png")
puts "Removing SVG file..."
system("rm test.svg")
puts "Moving file back..."
system("mv --update input.fasta #{file}")
