#!/usr/bin/env ruby

file = ARGV.shift
if file.nil? 
  puts "Usage: ruby runner.rb sequence.fasta"
  exit -1
end

puts "Moving file in place..."
`mv #{file} input.fasta`
puts "Creating SVG file \"test.svg\" from sequence..."
`rasem test.rasem`
puts "Converting SVG file to PNG file \"#{file}.png\"..."
`mogrify -format png test.svg`
`mv test.png #{file}.png`
puts "Removing SVG file..."
`rm test.svg`
puts "Moving file back..."
`mv input.fasta #{file}`
